export const SYSTEM_DEFAULTS = {
  PASSING_SCORE: 450,
  PAGE_SIZE: 50,
  MAX_PAGE_SIZE: 100,
  CERTIFICATE_VALIDITY_YEARS: 2,
  JWT_EXPIRES_IN: '1d',
  UPLOAD_MAX_FILE_SIZE: 10 * 1024 * 1024, // 10MB
} as const;

export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN_EPT: 'ADMIN_EPT',
  QUESTION_AUTHOR: 'QUESTION_AUTHOR',
  REVIEWER: 'REVIEWER',
  PROCTOR: 'PROCTOR',
  STUDENT: 'STUDENT',
  EXECUTIVE: 'EXECUTIVE',
} as const;

export type UserRole = (typeof USER_ROLES)[keyof typeof USER_ROLES];

export const MANAGEMENT_ROLES: UserRole[] = [
  USER_ROLES.SUPER_ADMIN,
  USER_ROLES.ADMIN_EPT,
  USER_ROLES.PROCTOR,
  USER_ROLES.EXECUTIVE,
];

export const ADMIN_ONLY_ROLES: UserRole[] = [
  USER_ROLES.SUPER_ADMIN,
  USER_ROLES.ADMIN_EPT,
];
