import { prisma } from '@starter-kit/database';

const db = prisma as any;

async function main() {
  console.log('🌱 Starting Realistic TOEFL ITP Exam Sample Seeding...');

  // 1. Clean up bad/obsolete sample questions
  console.log('🧹 Cleaning up bad and dummy questions from database...');
  const deletedQuestions = await db.question.deleteMany({});
  console.log(`   -> Deleted ${deletedQuestions.count} old questions.`);

  const deletedPassages = await db.passage.deleteMany({});
  console.log(`   -> Deleted ${deletedPassages.count} old passages.`);

  // 2. SEED SECTION 3 PASSAGES FIRST (So we have passage IDs for Reading questions)
  console.log('📖 Seeding Authentic Academic Reading Passages...');

  const passage1 = await db.passage.create({
    data: {
      title: "Continental Drift and Plate Tectonics: From Wegener's Hypothesis to Modern Geophysics",
      content: `In 1912, German meteorologist Alfred Wegener proposed the revolutionary hypothesis of continental drift, asserting that all of Earth's landmasses were once joined in a single primordial supercontinent that he christened Pangaea. According to Wegener, approximately two hundred million years ago, this gigantic landmass began fragmenting into smaller continental blocks that gradually drifted across the oceanic floor to their contemporary positions. To substantiate his contentious conjecture, Wegener marshaled an impressive array of empirical evidence. He highlighted the uncanny jigsaw-puzzle fit of the Atlantic coastlines of South America and Africa, and documented identical fossil remains—such as the freshwater reptile Mesosaurus and the fern Glossopteris—across widely separated continents that today possess drastically disparate climates. Furthermore, he demonstrated that continuous geological strata and ancient glacial deposits in South America, southern Africa, India, and Australia matched seamlessly when the continents were reassembled into a cohesive whole.

Despite this compelling body of paleontological and structural correlations, the established geological orthodoxy of the early twentieth century overwhelmingly rejected Wegener's hypothesis. The primary catalyst for this widespread skepticism was Wegener's inability to identify a plausible physical mechanism capable of propelling colossal sialic continental masses through the rigid basaltic oceanic crust. Wegener erroneously suggested that centrifugal forces generated by Earth's rotation and tidal attractions were responsible, calculations that physicists readily proved completely insufficient.

It was not until the 1960s that Wegener's foundational concepts were vindicated and synthesized into the modern paradigm of plate tectonics. Technological advancements during World War II and the Cold War enabled oceanographers to systematically map the ocean floor, revealing vast underwater mountain ranges known as mid-ocean ridges and deep oceanic trenches. Geophysicists Harry Hess and Robert Dietz formulated the theory of seafloor spreading, postulating that magma rises from the mantle along mid-ocean ridges, cooling to form new oceanic crust while pushing older crust laterally outward. Concurrently, paleomagnetic surveys demonstrated symmetrical alternating bands of magnetic reversals preserved in basaltic seafloor rocks on either side of the ridges, providing incontrovertible empirical proof that the seafloor was indeed moving. Today, plate tectonics is universally recognized as the unifying framework of modern geology.`,
    },
  });

  const passage2 = await db.passage.create({
    data: {
      title: 'The Maya Wetland Agroecosystems: Hydraulic Engineering in the Neotropical Lowlands',
      content: `For generations, twentieth-century archaeologists commonly believed that the ancient Maya civilization of Mesoamerica subsisted almost entirely on slash-and-burn, or swidden (milpa), agriculture. In this traditional extensive cultivation model, farmers clear patches of tropical forest, burn the dried vegetation to release nutrients into the thin, leached rainforest soil, cultivate maize and beans for several years, and subsequently leave the land fallow for prolonged periods to regenerate. While swidden farming can sustain modest, dispersed village populations, archaeological demographic reconstructions established that the southern Maya lowlands—encompassing northern Guatemala, Belize, and southeastern Mexico—supported densely populated urban centers such as Tikal and Calakmul, where urban density rivaled that of contemporary medieval European capitals. This glaring demographic paradox compelled researchers to investigate how such fragile tropical ecosystems could maintain millions of inhabitants during the Classic Period (250–900 CE).

Pioneering archaeological fieldwork and recent airborne light detection and ranging (LiDAR) laser surveys have radically dismantled the primitive swidden paradigm. Rather than depending on shifting forest plots, the ancient Maya developed sophisticated, labor-intensive agroengineering systems centered on wetland canal networks and raised fields (known locally as chinampas or bajo fields). In seasonal swamps and shallow river floodplains, Maya civil engineers excavated interconnected channels, heaping nutrient-rich organic muck and muck-clay sediments onto elevated rectangular planting beds.

This hydraulic agroecosystem conferred numerous strategic advantages. First, the elevated platforms kept crops above seasonal waterlogged floodwaters while providing constant sub-irrigation through capillary water seepage from adjoining canals during harsh dry seasons. Second, the canal waterways served as aquaculture nurseries for edible freshwater fish, turtles, and edible snails, supplying vital animal proteins to urban diets. Third, the aquatic vegetation and detritus accumulating in the canals provided a perpetually renewable organic fertilizer that farmers scooped up to replenish bed fertility, thereby eliminating the need for prolonged fallow cycles. Consequently, these engineered wetland agroecosystems generated unprecedented agricultural yields, providing the nutritional foundation that sustained the spectacular architectural, scientific, and cultural achievements of the classic Maya civilization.`,
    },
  });

  console.log(`   -> Created 2 Reading Passages: "${passage1.title}" and "${passage2.title}".`);

  // ==========================================
  // SECTION 1: LISTENING COMPREHENSION (18 SOAL)
  // ==========================================
  console.log('🎧 Seeding Realistic Listening Comprehension Questions with Real Audio...');

  const listeningQuestions = [
    // PART A: SHORT CONVERSATIONS (1 - 10)
    {
      section: 'LISTENING',
      listeningPart: 'PART_A',
      audioUrl: '/audio/listening_part_a_01.wav',
      questionText: 'What does the woman imply the man should do?',
      options: [
        { id: 'A', text: 'Wait for the next campus shuttle' },
        { id: 'B', text: 'Take the city bus on Green Street' },
        { id: 'C', text: 'Walk all the way to the north campus' },
        { id: 'D', text: 'Submit a complaint to the transportation office' },
      ],
      correctOption: 'B',
      explanation: 'Wanita menyatakan bahwa bus kota di Green Street beroperasi hingga tengah malam ("runs until midnight"), menyiratkan pria tersebut dapat menggunakan alternatif transportasi tersebut.',
      skillTag: 'Suggestions & Implied Action',
      difficulty: 'EASY',
      status: 'APPROVED',
      reviewNotes: 'Dialogue: Man asks if campus shuttle is running. Woman notes city bus runs until midnight.',
    },
    {
      section: 'LISTENING',
      listeningPart: 'PART_A',
      audioUrl: '/audio/listening_part_a_02.wav',
      questionText: 'What does the man suggest the woman do?',
      options: [
        { id: 'A', text: 'Study biology alone in her dorm room' },
        { id: 'B', text: 'Reschedule her biology examination' },
        { id: 'C', text: 'Join their evening study group at the library' },
        { id: 'D', text: 'Request private tutoring from the professor' },
      ],
      correctOption: 'C',
      explanation: 'Pria tersebut secara eksplisit mengajak wanita bergabung dengan kelompok belajar yang dibentuk di perpustakaan ("You are more than welcome to join").',
      skillTag: 'Invitations & Suggestions',
      difficulty: 'EASY',
      status: 'APPROVED',
      reviewNotes: 'Dialogue: Woman worried about midterm. Man invites her to library study group.',
    },
    {
      section: 'LISTENING',
      listeningPart: 'PART_A',
      audioUrl: '/audio/listening_part_a_03.wav',
      questionText: 'What does the woman mean?',
      options: [
        { id: 'A', text: 'Professor Wilson granted her a short extension' },
        { id: 'B', text: 'She decided to withdraw from the research seminar' },
        { id: 'C', text: 'The professor strictly refused to accept late submissions' },
        { id: 'D', text: 'She forgot to discuss the proposal with the professor' },
      ],
      correctOption: 'C',
      explanation: 'Kata "Hardly" dan frasa "deadlines are strictly non-negotiable" menunjukkan bahwa profesor menolak tegas permohonan perpanjangan waktu.',
      skillTag: 'Almost Negative Expressions',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
      reviewNotes: 'Dialogue: Man asks if extension was granted. Woman replies "Hardly. Deadlines are non-negotiable."',
    },
    {
      section: 'LISTENING',
      listeningPart: 'PART_A',
      audioUrl: '/audio/listening_part_a_04.wav',
      questionText: 'What does the man imply?',
      options: [
        { id: 'A', text: 'He was unable to submit his scholarship documents' },
        { id: 'B', text: 'He strongly agrees that the office was extremely crowded' },
        { id: 'C', text: 'He needs the woman to explain financial aid regulations' },
        { id: 'D', text: 'He arrived before the office opened' },
      ],
      correctOption: 'B',
      explanation: 'Idiom "Tell me about it!" menunjukkan kesepakatan penuh dengan lawan bicara bahwa kantor bantuan keuangan luar biasa padat antreannya.',
      skillTag: 'Agreement Expressions',
      difficulty: 'EASY',
      status: 'APPROVED',
      reviewNotes: 'Dialogue: Woman notes long line. Man replies "Tell me about it! Waited nearly an hour."',
    },
    {
      section: 'LISTENING',
      listeningPart: 'PART_A',
      audioUrl: '/audio/listening_part_a_05.wav',
      questionText: 'What does the woman suggest the man do?',
      options: [
        { id: 'A', text: 'Purchase the reference handbook online' },
        { id: 'B', text: 'Borrow the book from another university library' },
        { id: 'C', text: 'Scan the necessary chapters in the reserve room' },
        { id: 'D', text: 'Change the research topic to avoid the handbook' },
      ],
      correctOption: 'C',
      explanation: 'Wanita menyarankan pemanfaatan alat pemindai (scanner) gratis di ruangan reserve untuk menyimpan bab buku yang dibutuhkan dalam format PDF.',
      skillTag: 'Problem Solving & Recommendations',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
      reviewNotes: 'Dialogue: Book is non-circulating. Woman suggests scanning chapters in the reserve room.',
    },
    {
      section: 'LISTENING',
      listeningPart: 'PART_A',
      audioUrl: '/audio/listening_part_a_06.wav',
      questionText: 'What does the man indicate about the geology excursion?',
      options: [
        { id: 'A', text: 'The excursion will most likely be postponed' },
        { id: 'B', text: 'The students should wear heavy waterproof boots' },
        { id: 'C', text: 'The weather forecast is usually unreliable' },
        { id: 'D', text: 'The hike will proceed despite the thunderstorms' },
      ],
      correctOption: 'A',
      explanation: 'Idiom "take a rain check" berarti menunda suatu acara atau kegiatan ke waktu mendatang akibat kendala cuaca buruk.',
      skillTag: 'Idioms & Future Actions',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
      reviewNotes: 'Dialogue: Forecast shows thunderstorms. Man says "take a rain check on that mountain hike."',
    },
    {
      section: 'LISTENING',
      listeningPart: 'PART_A',
      audioUrl: '/audio/listening_part_a_07.wav',
      questionText: "What is the woman's main concern?",
      options: [
        { id: 'A', text: 'She is dissatisfied with the internship compensation' },
        { id: 'B', text: 'She has undertaken more commitments than she can handle' },
        { id: 'C', text: 'Her department rejected her laboratory internship credits' },
        { id: 'D', text: 'She lacks technical preparation for laboratory tasks' },
      ],
      correctOption: 'B',
      explanation: 'Idiom "bitten off more than I can chew" bermakna mengambil tanggung jawab atau beban yang melampaui kemampuan untuk menyelesaikannya dengan baik.',
      skillTag: 'Idioms & Emotional State',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
      reviewNotes: 'Dialogue: Taking 18 credits and internship. Woman says she bit off more than she could chew.',
    },
    {
      section: 'LISTENING',
      listeningPart: 'PART_A',
      audioUrl: '/audio/listening_part_a_08.wav',
      questionText: 'What does the man imply about his notes?',
      options: [
        { id: 'A', text: 'He did not take notes during the lecture' },
        { id: 'B', text: 'His notebook was left in the lecture hall' },
        { id: 'C', text: 'His handwriting is too untidy to be legible' },
        { id: 'D', text: 'He already shared his notes with another student' },
      ],
      correctOption: 'C',
      explanation: 'Frasa "my shorthand is such a mess that even I can barely make heads or tails of it" berarti catatan tulisan tangannya terlalu berantakan dan sulit dibaca.',
      skillTag: 'Implied Meaning & Idioms',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
      reviewNotes: 'Dialogue: Woman asks for lecture notes. Man says his messy shorthand cannot be deciphered.',
    },
    {
      section: 'LISTENING',
      listeningPart: 'PART_A',
      audioUrl: '/audio/listening_part_a_09.wav',
      questionText: 'What does the woman mean?',
      options: [
        { id: 'A', text: 'She has already moved into the university dormitory' },
        { id: 'B', text: 'The opportunity to apply for on-campus housing has passed' },
        { id: 'C', text: 'She intends to travel by ship during the academic break' },
        { id: 'D', text: 'She cannot afford the student dormitory fees' },
      ],
      correctOption: 'B',
      explanation: 'Idiom "that ship has sailed" menyatakan bahwa peluang sudah tertutup karena batas waktu pendaftaran asrama kampus telah berakhir Jumat lalu.',
      skillTag: 'Idiomatic Expressions',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
      reviewNotes: 'Dialogue: Woman wanted dorm housing, but deadline closed Friday: "that ship has sailed."',
    },
    {
      section: 'LISTENING',
      listeningPart: 'PART_A',
      audioUrl: '/audio/listening_part_a_10.wav',
      questionText: 'What does the man mean?',
      options: [
        { id: 'A', text: 'He wants the woman to repeat her statement' },
        { id: 'B', text: 'He found the lecture difficult to comprehend' },
        { id: 'C', text: 'He enthusiastically agrees that the lecture was fascinating' },
        { id: 'D', text: 'He has conducted research on neural plasticity before' },
      ],
      correctOption: 'C',
      explanation: 'Idiom "You can say that again!" mengekspresikan persetujuan yang sangat antusias dan mendalam atas opini lawan bicara.',
      skillTag: 'Agreement Expressions',
      difficulty: 'EASY',
      status: 'APPROVED',
      reviewNotes: 'Dialogue: Lecture was fascinating. Man replies "You can say that again!"',
    },

    // PART B: LONGER CONVERSATION (11 - 14)
    {
      section: 'LISTENING',
      listeningPart: 'PART_B',
      audioUrl: '/audio/listening_part_b_01.wav',
      questionText: "What is the primary purpose of the student's visit to the academic advisor?",
      options: [
        { id: 'A', text: 'To request financial assistance for tuition fees' },
        { id: 'B', text: 'To resolve an enrollment blockage for an advanced chemistry course' },
        { id: 'C', text: 'To apply for a laboratory assistant position' },
        { id: 'D', text: 'To change her undergraduate major' },
      ],
      correctOption: 'B',
      explanation: 'Mahasiswi mendatangi dosen penasihat untuk mengatasi kendala registrasi mata kuliah Advanced Environmental Chemistry yang terblokir sistem prasyarat.',
      skillTag: 'Main Topic & Purpose',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
      reviewNotes: 'Part B: Consultation regarding prerequisite override for registration.',
    },
    {
      section: 'LISTENING',
      listeningPart: 'PART_B',
      audioUrl: '/audio/listening_part_b_01.wav',
      questionText: "Why did the university registration system flag the student's enrollment?",
      options: [
        { id: 'A', text: 'She had not paid her semester tuition fees' },
        { id: 'B', text: 'Her transferred laboratory credits were not officially mapped in the database' },
        { id: 'C', text: 'She failed General Chemistry at her previous institution' },
        { id: 'D', text: 'The course registration period had already expired' },
      ],
      correctOption: 'B',
      explanation: 'Sistem menolak karena nilai praktikum kimia organik dari kampus sebelumnya belum terpetakan secara resmi di database universitas.',
      skillTag: 'Factual Details',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
      reviewNotes: 'Part B: Community college transfer credit mapping issue.',
    },
    {
      section: 'LISTENING',
      listeningPart: 'PART_B',
      audioUrl: '/audio/listening_part_b_01.wav',
      questionText: 'What does the advisor instruct the student to bring to his office?',
      options: [
        { id: 'A', text: 'A recommendation letter from her former dean' },
        { id: 'B', text: 'The official syllabus and laboratory transcript from the community college' },
        { id: 'C', text: 'A signed petition from her classmates' },
        { id: 'D', text: 'Her original high school diploma' },
      ],
      correctOption: 'B',
      explanation: 'Dosen penasihat meminta mahasiswi membawa silabus resmi dan transkrip lab ("official course syllabus and your lab transcript") guna menandatangani formulir override.',
      skillTag: 'Action Details',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
      reviewNotes: 'Part B: Required documents for prerequisite waiver override.',
    },
    {
      section: 'LISTENING',
      listeningPart: 'PART_B',
      audioUrl: '/audio/listening_part_b_01.wav',
      questionText: 'Why is time critical for the student to submit the documentation?',
      options: [
        { id: 'A', text: 'The academic advisor is going on sabbatical next week' },
        { id: 'B', text: 'The class capacity is nearly full and overrides cannot exceed the limit' },
        { id: 'C', text: 'The final examination is scheduled for tomorrow' },
        { id: 'D', text: 'The university will cancel her student visa' },
      ],
      correctOption: 'B',
      explanation: 'Kapasitas kelas hanya 30 kursi dan 25 sudah terisi. Jika kuota penuh, formulir override penasihat pun tidak dapat menjamin kursi.',
      skillTag: 'Inference & Context',
      difficulty: 'HARD',
      status: 'APPROVED',
      reviewNotes: 'Part B: Time sensitivity due to class seat quota.',
    },

    // PART C: ACADEMIC MINI-LECTURE (15 - 18)
    {
      section: 'LISTENING',
      listeningPart: 'PART_C',
      audioUrl: '/audio/listening_part_c_01.wav',
      questionText: 'What is the main subject of the earth science lecture?',
      options: [
        { id: 'A', text: 'The volcanic origins of Martian mountain ranges' },
        { id: 'B', text: 'The wind-sculpted geological landforms known as yardangs' },
        { id: 'C', text: 'The chemical composition of desert sand dunes' },
        { id: 'D', text: 'Modern techniques for measuring soil erosion in valleys' },
      ],
      correctOption: 'B',
      explanation: 'Kuliah berfokus pada bentang alam erosi angin di lingkungan arid yang dinamakan yardang, baik di bumi maupun di Mars.',
      skillTag: 'Main Idea / Lecture Topic',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
      reviewNotes: 'Part C: Lecture on yardangs and aeolian deflation.',
    },
    {
      section: 'LISTENING',
      listeningPart: 'PART_C',
      audioUrl: '/audio/listening_part_c_01.wav',
      questionText: 'According to the professor, how do yardangs differ fundamentally from sand dunes?',
      options: [
        { id: 'A', text: 'Yardangs are erosional structures, whereas dunes are depositional landforms' },
        { id: 'B', text: 'Yardangs only form underwater, whereas dunes form on dry land' },
        { id: 'C', text: 'Yardangs consist entirely of loose sand grains' },
        { id: 'D', text: 'Yardangs are created exclusively by glacial movement' },
      ],
      correctOption: 'A',
      explanation: 'Dosen membedakan bahwa gumuk pasir (dunes) adalah bentang alam pengendapan (depositional), sedangkan yardang merupakan bentang alam hasil pengikisan/erosi batuan (erosional).',
      skillTag: 'Comparison & Detail',
      difficulty: 'HARD',
      status: 'APPROVED',
      reviewNotes: 'Part C: Yardangs (erosional) vs sand dunes (depositional).',
    },
    {
      section: 'LISTENING',
      listeningPart: 'PART_C',
      audioUrl: '/audio/listening_part_c_01.wav',
      questionText: 'What physical object does the professor compare the shape of a mature yardang to?',
      options: [
        { id: 'A', text: 'A pyramid with carved ridges' },
        { id: 'B', text: 'The inverted hull of a boat' },
        { id: 'C', text: 'An aerodynamic aircraft wing' },
        { id: 'D', text: 'A mushroom-shaped boulder' },
      ],
      correctOption: 'B',
      explanation: 'Dosen menyatakan bahwa bentuk aerodinamis yardang menyerupai lambung perahu yang terbalik ("the inverted hull of a boat").',
      skillTag: 'Factual Detail / Analogies',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
      reviewNotes: 'Part C: Morphological resemblance to an inverted boat hull.',
    },
    {
      section: 'LISTENING',
      listeningPart: 'PART_C',
      audioUrl: '/audio/listening_part_c_01.wav',
      questionText: 'Why are planetary scientists interested in examining yardangs on Mars?',
      options: [
        { id: 'A', text: 'To verify the presence of active water bodies on the surface' },
        { id: 'B', text: 'To gain insights into historical atmospheric density and ancient wind patterns' },
        { id: 'C', text: 'To extract valuable mineral ores for future colonies' },
        { id: 'D', text: 'To prove that vegetation once covered the Martian equatorial plains' },
      ],
      correctOption: 'B',
      explanation: 'Pemeriksaan yardang di Mars memberikan informasi berharga bagi ilmuwan tentang kerapatan atmosfer masa lalu dan pola sirkulasi angin di planet merah.',
      skillTag: 'Academic Inference',
      difficulty: 'HARD',
      status: 'APPROVED',
      reviewNotes: 'Part C: Studying Martian yardangs to reconstruct paleo-atmospheric wind patterns.',
    },
  ];

  for (const q of listeningQuestions) {
    await db.question.create({ data: q });
  }
  console.log(`   -> Created ${listeningQuestions.length} Listening questions.`);

  // ==========================================
  // SECTION 2: STRUCTURE & WRITTEN EXPRESSION (20 SOAL)
  // ==========================================
  console.log('✍️ Seeding Structure & Written Expression Questions...');

  const structureQuestions = [
    // PART A: SENTENCE COMPLETION (19 - 28)
    {
      section: 'STRUCTURE',
      questionText: 'The dean of the academic faculty, accompanied by several department chairs, _______ currently attending the international higher education symposium in Singapore.',
      options: [
        { id: 'A', text: 'are' },
        { id: 'B', text: 'is' },
        { id: 'C', text: 'were' },
        { id: 'D', text: 'have been' },
      ],
      correctOption: 'B',
      explanation: 'Subjek sejati kalimat adalah "The dean" (tunggal/singular). Frasa "accompanied by several department chairs" adalah penjelas preposisional yang tidak mempengaruhi jumlah kata kerja.',
      skillTag: 'Subject-Verb Agreement',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
    },
    {
      section: 'STRUCTURE',
      questionText: 'Not only _______ the national science competition with distinction, but she also secured a prestigious research fellowship at Cambridge University.',
      options: [
        { id: 'A', text: 'she won' },
        { id: 'B', text: 'did she win' },
        { id: 'C', text: 'won she' },
        { id: 'D', text: 'she did win' },
      ],
      correctOption: 'B',
      explanation: 'Inversi wajib diterapkan bila kalimat diawali dengan frasa adverbial negatif atau pembatas seperti "Not only". Polanya adalah auxiliary verb + Subject + Bare Verb ("did she win").',
      skillTag: 'Inversion after Negative Expressions',
      difficulty: 'HARD',
      status: 'APPROVED',
    },
    {
      section: 'STRUCTURE',
      questionText: 'The ethics committee strictly mandated that the principal investigator _______ all clinical trial records to the oversight board before Friday.',
      options: [
        { id: 'A', text: 'submits' },
        { id: 'B', text: 'submitted' },
        { id: 'C', text: 'submit' },
        { id: 'D', text: 'is submitting' },
      ],
      correctOption: 'C',
      explanation: 'Klausa setelah kata kerja penuntut mandat/anjuran (subjunctive mood) seperti "mandated that" mewajibkan penggunaan kata kerja bentuk dasar (bare infinitive / V1 tanpa akhiran -s).',
      skillTag: 'Subjunctive Mood',
      difficulty: 'HARD',
      status: 'APPROVED',
    },
    {
      section: 'STRUCTURE',
      questionText: 'The faster the aerodynamic airflow travels over the upper curved surface of an aircraft wing, _______ the atmospheric pressure above it becomes.',
      options: [
        { id: 'A', text: 'the lower' },
        { id: 'B', text: 'lower' },
        { id: 'C', text: 'lowest' },
        { id: 'D', text: 'the lowest' },
      ],
      correctOption: 'A',
      explanation: 'Struktur komparatif berpasangan (double comparative) menggunakan pola sejajar: "The + comparative..., the + comparative...".',
      skillTag: 'Correlative Comparatives',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
    },
    {
      section: 'STRUCTURE',
      questionText: 'Mount Tambora, _______ on the island of Sumbawa in modern Indonesia, generated the catastrophic 1815 eruption that caused the global "Year Without a Summer."',
      options: [
        { id: 'A', text: 'located' },
        { id: 'B', text: 'is located' },
        { id: 'C', text: 'which locating' },
        { id: 'D', text: 'that located' },
      ],
      correctOption: 'A',
      explanation: 'Bentuk pemendekan klausa ajektiva pasif (reduced relative clause): "(which is) located on the island of Sumbawa". Memilih "is located" akan menyebabkan double verb pada kalimat utama.',
      skillTag: 'Reduced Adjective Clauses',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
    },
    {
      section: 'STRUCTURE',
      questionText: 'Had the geotechnical engineers _______ the subterranean aquifer beneath the excavation site, the foundation collapse could have been averted.',
      options: [
        { id: 'A', text: 'detect' },
        { id: 'B', text: 'detected' },
        { id: 'C', text: 'detecting' },
        { id: 'D', text: 'detects' },
      ],
      correctOption: 'B',
      explanation: 'Inversi pengandaian tipe 3 (past unreal conditional): "Had + Subject + Past Participle (V3)" yang menggantikan "If the geotechnical engineers had detected...".',
      skillTag: 'Inverted Conditionals',
      difficulty: 'HARD',
      status: 'APPROVED',
    },
    {
      section: 'STRUCTURE',
      questionText: 'An effective academic dissertation requires not only rigorous empirical research _______ a lucid and coherent analytical synthesis.',
      options: [
        { id: 'A', text: 'but also' },
        { id: 'B', text: 'and also' },
        { id: 'C', text: 'as well as' },
        { id: 'D', text: 'but neither' },
      ],
      correctOption: 'A',
      explanation: 'Konjungsi berpasangan (correlative conjunction) untuk "not only" adalah "but also" yang menghubungkan dua frasa nomina sejajar.',
      skillTag: 'Parallel Structure & Correlatives',
      difficulty: 'EASY',
      status: 'APPROVED',
    },
    {
      section: 'STRUCTURE',
      questionText: 'What astonished the observational astrophysicists most _______ the unexpected orbital deceleration of the interstellar comet.',
      options: [
        { id: 'A', text: 'were' },
        { id: 'B', text: 'was' },
        { id: 'C', text: 'are' },
        { id: 'D', text: 'have been' },
      ],
      correctOption: 'B',
      explanation: 'Noun clause yang diawali "What" dan bertindak sebagai subjek kalimat dianggap tunggal (singular) sehingga membutuhkan to be "was".',
      skillTag: 'Noun Clauses as Subject',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
    },
    {
      section: 'STRUCTURE',
      questionText: 'The university laboratory supervisor had each doctoral student _______ an extensive safety risk assessment prior to commencing hazardous experiments.',
      options: [
        { id: 'A', text: 'completing' },
        { id: 'B', text: 'to complete' },
        { id: 'C', text: 'complete' },
        { id: 'D', text: 'completed' },
      ],
      correctOption: 'C',
      explanation: 'Kata kerja kausatif aktif "have + someone + bare infinitive (V1)": "had each doctoral student complete...".',
      skillTag: 'Causative Verbs',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
    },
    {
      section: 'STRUCTURE',
      questionText: 'Rarely _______ such an abrupt and transformative paradigm shift in theoretical physics occurred within a single decade.',
      options: [
        { id: 'A', text: 'has' },
        { id: 'B', text: 'have' },
        { id: 'C', text: 'having' },
        { id: 'D', text: 'was' },
      ],
      correctOption: 'A',
      explanation: 'Inversi dengan adverbia negatif "Rarely". Subjek kalimat adalah "such an abrupt paradigm shift" (singular), sehingga auxiliary yang tepat untuk present perfect adalah "has".',
      skillTag: 'Inversion with Negative Adverbs',
      difficulty: 'HARD',
      status: 'APPROVED',
    },

    // PART B: ERROR IDENTIFICATION (29 - 38)
    {
      section: 'STRUCTURE',
      questionText: 'The human brain is (A) composed of (B) billions of neurons that (C) communicates with one another via (D) electrical impulses.',
      options: [
        { id: 'A', text: '(A) composed of' },
        { id: 'B', text: '(B) billions of' },
        { id: 'C', text: '(C) communicates' },
        { id: 'D', text: '(D) electrical impulses' },
      ],
      correctOption: 'C',
      explanation: 'Pilihan (C) salah. Anteseden dari relative pronoun "that" adalah jamak ("billions of neurons"), sehingga kata kerja penjelas harus jamak ("communicate", bukan "communicates").',
      skillTag: 'Agreement in Relative Clauses',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
    },
    {
      section: 'STRUCTURE',
      questionText: 'Although photosynthesis (A) requires sunlight, water, and carbon dioxide, the chemical reactions (B) themselves (C) can occur either during daylight or (D) in night.',
      options: [
        { id: 'A', text: '(A) requires' },
        { id: 'B', text: '(B) themselves' },
        { id: 'C', text: '(C) can occur' },
        { id: 'D', text: '(D) in night' },
      ],
      correctOption: 'D',
      explanation: 'Pilihan (D) salah secara preposisi waktu. Bentuk baku dalam bahasa Inggris adalah "at night", bukan "in night".',
      skillTag: 'Preposition Usage',
      difficulty: 'EASY',
      status: 'APPROVED',
    },
    {
      section: 'STRUCTURE',
      questionText: 'Neither the department chair (A) nor the faculty members (B) was (C) willing to compromise on the (D) proposed curriculum revision.',
      options: [
        { id: 'A', text: '(A) nor' },
        { id: 'B', text: '(B) was' },
        { id: 'C', text: '(C) willing to' },
        { id: 'D', text: '(D) proposed' },
      ],
      correctOption: 'B',
      explanation: 'Pilihan (B) salah. Dalam aturan "neither... nor...", konjugasi to be mengikuti subjek kedua/terdekat yaitu "the faculty members" (jamak), sehingga kata kerjanya harus "were".',
      skillTag: 'Subject-Verb Agreement with Correlatives',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
    },
    {
      section: 'STRUCTURE',
      questionText: 'The Mariana Trench is (A) considerably (B) more deeper (C) than any other geographical canyon located on the (D) Earth surface.',
      options: [
        { id: 'A', text: '(A) considerably' },
        { id: 'B', text: '(B) more deeper' },
        { id: 'C', text: '(C) than any other' },
        { id: 'D', text: '(D) Earth surface' },
      ],
      correctOption: 'B',
      explanation: 'Pilihan (B) salah karena merupakan double comparative. Kata "deep" hanya memiliki 1 suku kata sehingga bentuk komparatifnya adalah "deeper" tanpa kata "more".',
      skillTag: 'Double Comparatives',
      difficulty: 'EASY',
      status: 'APPROVED',
    },
    {
      section: 'STRUCTURE',
      questionText: 'Fossils of prehistoric deciduous trees (A) have discovered (B) in Antarctica, proving that the frozen continent once (C) experienced a much warmer (D) climate.',
      options: [
        { id: 'A', text: '(A) have discovered' },
        { id: 'B', text: '(B) in Antarctica' },
        { id: 'C', text: '(C) experienced' },
        { id: 'D', text: '(D) climate' },
      ],
      correctOption: 'A',
      explanation: 'Pilihan (A) keliru dalam makna gramatikal pasif. Fosil tidak menemukan, melainkan ditemukan oleh para peneliti, sehingga bentuk yang benar adalah pasif: "have been discovered".',
      skillTag: 'Passive Voice',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
    },
    {
      section: 'STRUCTURE',
      questionText: 'Because its (A) dense atmosphere retains solar radiation, Venus has a surface temperature (B) significantly hotter (C) than that of any (D) another planet in the solar system.',
      options: [
        { id: 'A', text: '(A) dense atmosphere' },
        { id: 'B', text: '(B) significantly hotter' },
        { id: 'C', text: '(C) than that of' },
        { id: 'D', text: '(D) another' },
      ],
      correctOption: 'D',
      explanation: 'Pilihan (D) salah. Setelah "any" dalam perbandingan komparatif dengan anggota kelompok yang sama, penentu yang baku adalah "other" ("any other planet"), bukan "another".',
      skillTag: 'Comparative Adjectives & Determiners',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
    },
    {
      section: 'STRUCTURE',
      questionText: 'The federal charter (A) mandates that a comprehensive national census (B) is conducted (C) every ten years to determine legislative (D) apportionment.',
      options: [
        { id: 'A', text: '(A) mandates that' },
        { id: 'B', text: '(B) is conducted' },
        { id: 'C', text: '(C) every ten years' },
        { id: 'D', text: '(D) apportionment' },
      ],
      correctOption: 'B',
      explanation: 'Pilihan (B) salah. Kata kerja perintah institusional "mandates that" mewajibkan bentuk subjunctive pasif, yaitu "(should) be conducted", bukan "is conducted".',
      skillTag: 'Subjunctive Passive Voice',
      difficulty: 'HARD',
      status: 'APPROVED',
    },
    {
      section: 'STRUCTURE',
      questionText: 'Not only (A) did the archaeologist discovered (B) intact ceremonial earthenware, but he also (C) uncovered fragments of Bronze Age metallic (D) weaponry.',
      options: [
        { id: 'A', text: '(A) did the archaeologist discovered' },
        { id: 'B', text: '(B) intact ceremonial' },
        { id: 'C', text: '(C) uncovered fragments' },
        { id: 'D', text: '(D) weaponry' },
      ],
      correctOption: 'A',
      explanation: 'Pilihan (A) salah. Dalam pembalikan kalimat dengan kata kerja bantu lampau "did", kata kerja utama harus kembali ke bare infinitive ("did the archaeologist discover").',
      skillTag: 'Inversion Auxiliary Rules',
      difficulty: 'HARD',
      status: 'APPROVED',
    },
    {
      section: 'STRUCTURE',
      questionText: 'Microscopic analysis (A) reveals that the crystalline lattice (B) of diamond makes it the (C) harder known natural mineral substance (D) on our planet.',
      options: [
        { id: 'A', text: '(A) reveals that' },
        { id: 'B', text: '(B) of diamond' },
        { id: 'C', text: '(C) harder' },
        { id: 'D', text: '(D) on our planet' },
      ],
      correctOption: 'C',
      explanation: 'Pilihan (C) salah. Karena terdapat penanda artikel "the" dan mencakup seluruh zat mineral di bumi, bentuk yang wajib digunakan adalah superlatif ("hardest"), bukan komparatif "harder".',
      skillTag: 'Superlative Adjectives',
      difficulty: 'EASY',
      status: 'APPROVED',
    },
    {
      section: 'STRUCTURE',
      questionText: 'The international trading consortium (A) which headquarters (B) are situated in Geneva has recently announced plans (C) to expand its operations (D) throughout Southeast Asia.',
      options: [
        { id: 'A', text: '(A) which' },
        { id: 'B', text: '(B) are situated' },
        { id: 'C', text: '(C) to expand' },
        { id: 'D', text: '(D) throughout' },
      ],
      correctOption: 'A',
      explanation: 'Pilihan (A) salah. Kata ganti penghubung kepemilikan (possessive relative pronoun) yang menghubungkan konsorsium dan kantor pusatnya adalah "whose" ("whose headquarters are situated...").',
      skillTag: 'Relative Pronouns',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
    },
  ];

  for (const q of structureQuestions) {
    await db.question.create({ data: q });
  }
  console.log(`   -> Created ${structureQuestions.length} Structure questions.`);

  // ==========================================
  // SECTION 3: READING COMPREHENSION (10 SOAL)
  // ==========================================
  console.log('📚 Seeding Reading Comprehension Questions tied to Passages...');

  const readingQuestions = [
    // PASSAGE 1 QUESTIONS (39 - 43)
    {
      section: 'READING',
      passageId: passage1.id,
      questionText: 'What is the primary purpose of the passage?',
      options: [
        { id: 'A', text: 'To explain how fossilization preserved specimens of Mesosaurus' },
        { id: 'B', text: "To trace the evolution of continental drift from Wegener's rejected hypothesis to the established paradigm of plate tectonics" },
        { id: 'C', text: 'To compare the geological topography of South America with that of southern Africa' },
        { id: 'D', text: 'To argue that Alfred Wegener was solely responsible for formulating modern plate tectonic theory' },
      ],
      correctOption: 'B',
      explanation: 'Wacana secara utuh merangkum perjalanan gagasan pergeseran benua dari hipotesis awal Wegener yang sempat ditolak hingga pembuktian dan penerimaannya dalam tektonik lempeng modern.',
      skillTag: 'Main Idea / Primary Purpose',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
    },
    {
      section: 'READING',
      passageId: passage1.id,
      questionText: 'According to paragraph 2, why did early twentieth-century geologists primarily reject Wegener’s hypothesis?',
      options: [
        { id: 'A', text: 'He lacked evidence of identical fossil specimens on different continents' },
        { id: 'B', text: 'His mapping of the Atlantic coastlines was proven to be geographically inaccurate' },
        { id: 'C', text: 'He failed to provide a scientifically plausible physical mechanism for continental movement' },
        { id: 'D', text: 'Modern seafloor spreading technology had already disproved his calculations' },
      ],
      correctOption: 'C',
      explanation: 'Paragraf 2 menyatakan bahwa penyebab utama penolakan adalah ketidakmampuan Wegener mengidentifikasi mekanisme fisik yang masuk akal ("inability to identify a plausible physical mechanism").',
      skillTag: 'Factual Detail',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
    },
    {
      section: 'READING',
      passageId: passage1.id,
      questionText: 'The word "compelling" in paragraph 2 is closest in meaning to:',
      options: [
        { id: 'A', text: 'persuasive' },
        { id: 'B', text: 'forceful' },
        { id: 'C', text: 'complicated' },
        { id: 'D', text: 'questionable' },
      ],
      correctOption: 'A',
      explanation: 'Dalam konteks "compelling body of paleontological correlations", kata "compelling" bermakna meyakinkan atau persuasif (persuasive).',
      skillTag: 'Vocabulary in Context',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
    },
    {
      section: 'READING',
      passageId: passage1.id,
      questionText: 'The word "their" in paragraph 1 refers to:',
      options: [
        { id: 'A', text: "Earth's landmasses" },
        { id: 'B', text: 'oceanic floors' },
        { id: 'C', text: 'smaller continental blocks' },
        { id: 'D', text: 'fossil remains' },
      ],
      correctOption: 'C',
      explanation: 'Kalimat pada paragraf 1 menyatakan: "...this gigantic landmass began fragmenting into smaller continental blocks that gradually drifted across the oceanic floor to their contemporary positions." Kata "their" merujuk pada "smaller continental blocks".',
      skillTag: 'Pronoun Reference',
      difficulty: 'EASY',
      status: 'APPROVED',
    },
    {
      section: 'READING',
      passageId: passage1.id,
      questionText: 'It can be inferred from paragraph 3 that the confirmation of seafloor spreading was largely enabled by:',
      options: [
        { id: 'A', text: 'Discoveries of dinosaur footprints along mid-ocean ridges' },
        { id: 'B', text: 'New oceanic mapping technologies and paleomagnetic surveys conducted during the mid-twentieth century' },
        { id: 'C', text: "Re-evaluating Wegener's calculations of tidal forces" },
        { id: 'D', text: 'Deep-sea diamond mining off the coast of Australia' },
      ],
      correctOption: 'B',
      explanation: 'Paragraf 3 menguraikan bahwa kemajuan teknologi pemetaan dasar laut era Perang Dunia II dan survei paleomagnetiklah yang memberikan bukti empiris tak terbantahkan atas pemekaran dasar samudra.',
      skillTag: 'Academic Inference',
      difficulty: 'HARD',
      status: 'APPROVED',
    },

    // PASSAGE 2 QUESTIONS (44 - 48)
    {
      section: 'READING',
      passageId: passage2.id,
      questionText: 'What is the main topic of the passage?',
      options: [
        { id: 'A', text: 'The religious ceremonies practiced in classical Maya city centers' },
        { id: 'B', text: 'The sophisticated wetland agricultural engineering systems developed by the ancient Maya' },
        { id: 'C', text: 'The military conflicts between the city-states of Tikal and Calakmul' },
        { id: 'D', text: 'Modern deforestation challenges facing Central American rainforests' },
      ],
      correctOption: 'B',
      explanation: 'Wacana membahas bagaimana peradaban Maya kuno merekayasa ekosistem lahan basah dan kanal buatan (raised fields) untuk menopang ketahanan pangan kota-kota padat penduduk.',
      skillTag: 'Main Topic',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
    },
    {
      section: 'READING',
      passageId: passage2.id,
      questionText: 'According to paragraph 1, what created the "demographic paradox" for early archaeologists?',
      options: [
        { id: 'A', text: 'The absence of architectural monuments in densely populated regions' },
        { id: 'B', text: 'The inability of basic slash-and-burn farming to feed the dense urban populations revealed by archaeological data' },
        { id: 'C', text: 'The rapid migration of European populations into Mesoamerican cities' },
        { id: 'D', text: 'The high life expectancy of farmers compared to royal aristocrats' },
      ],
      correctOption: 'B',
      explanation: 'Paradoks demografis muncul karena model pertanian ladang berpindah (swidden) dinilai tidak mungkin mampu menyuplai pangan bagi jutaan penduduk perkotaan sepadat Tikal dan Calakmul.',
      skillTag: 'Factual Detail',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
    },
    {
      section: 'READING',
      passageId: passage2.id,
      questionText: 'The word "sophisticated" in paragraph 2 is closest in meaning to:',
      options: [
        { id: 'A', text: 'complex and highly developed' },
        { id: 'B', text: 'expensive and wasteful' },
        { id: 'C', text: 'simple and temporary' },
        { id: 'D', text: 'dangerous to construct' },
      ],
      correctOption: 'A',
      explanation: 'Kata "sophisticated" dalam konteks rekayasa sistem agroekologi bermakna kompleks, maju, dan sangat berkembang (complex and highly developed).',
      skillTag: 'Vocabulary in Context',
      difficulty: 'EASY',
      status: 'APPROVED',
    },
    {
      section: 'READING',
      passageId: passage2.id,
      questionText: 'According to paragraph 3, which of the following is NOT mentioned as an advantage of the Maya wetland canal system?',
      options: [
        { id: 'A', text: 'Sub-irrigation of crops through capillary water action during dry seasons' },
        { id: 'B', text: 'Breeding freshwater fish and aquatic animals for dietary protein' },
        { id: 'C', text: 'Generating hydroelectric energy to grind maize kernels' },
        { id: 'D', text: 'Producing nutrient-rich canal muck used as renewable fertilizer' },
      ],
      correctOption: 'C',
      explanation: 'Pilihan (C) tidak pernah disebutkan dalam wacana. Tiga manfaat lainnya (sub-irigasi kapiler, akuakultur protein hewani, dan pupuk organik dari lumpur kanal) dijelaskan secara spesifik.',
      skillTag: 'Negative Factual Detail',
      difficulty: 'MEDIUM',
      status: 'APPROVED',
    },
    {
      section: 'READING',
      passageId: passage2.id,
      questionText: 'The author implies that the sophisticated hydraulic raised-field systems:',
      options: [
        { id: 'A', text: 'Were constructed entirely after the arrival of Spanish colonists' },
        { id: 'B', text: 'Enabled the Maya to cultivate crops continuously without leaving agricultural fields fallow for years' },
        { id: 'C', text: 'Caused catastrophic environmental destruction that immediately triggered the collapse of Tikal' },
        { id: 'D', text: 'Were less productive than traditional shifting swidden plots' },
      ],
      correctOption: 'B',
      explanation: 'Paragraf 3 mengindikasikan bahwa dengan kesuburan tanah yang terus diperbarui oleh lumpur kanal, para petani dapat mengeliminasi siklus lahan bero yang panjang ("eliminating the need for prolonged fallow cycles").',
      skillTag: 'Academic Inference',
      difficulty: 'HARD',
      status: 'APPROVED',
    },
  ];

  for (const q of readingQuestions) {
    await db.question.create({ data: q });
  }
  console.log(`   -> Created ${readingQuestions.length} Reading questions.`);

  // 3. Final Verification Count
  const total = await db.question.count();
  const bySection = await db.question.groupBy({
    by: ['section'],
    _count: { id: true },
  });

  console.log('✅ Realistic Question Seeding Complete!');
  console.log(`   Total Questions: ${total}`);
  console.log('   Breakdown by Section:', bySection);
}

main()
  .catch((e) => {
    console.error('❌ Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
